# Generated by Django 4.0.4 on 2022-09-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0002_class_grade_test_worksheet_delete_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='worksheet',
        ),
        migrations.RemoveField(
            model_name='test',
            name='_class',
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='student',
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='test',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='WorkSheet',
        ),
    ]
